/**
 * Loads the baked connection and occupancy sets, once per session.
 *
 * These are what turn a cold part from a twenty-request tree walk into a map lookup: the
 * whole annotated corpus arrives in two files, so snapping and collision are available
 * for any covered part the moment the app is up. See `docs/PREBAKE.md`.
 *
 * Missing or unreadable files are not an error. `public/baked/` is generated by
 * `npm run prebake` and deliberately untracked, so a fresh clone has none of it; a bake
 * made at a different format version or voxel size is rejected by the readers in
 * `src/snap/baked.ts` for the same reason. Either way the maps come back empty and the
 * caller resolves from source instead — slower, identical results.
 */

import { unpackConnections, unpackOccupancy } from '../snap/baked.ts';
import type { ConnectionPoint, OccupancyMask } from '../snap/types.ts';
import type { Bounds } from '../types.ts';

export interface BakedParts {
  connections: ReadonlyMap<string, ConnectionPoint[]>;
  occupancy: ReadonlyMap<string, { bounds: Bounds; occupancy: OccupancyMask }>;
}

const EMPTY: BakedParts = { connections: new Map(), occupancy: new Map() };

async function fetchBinary(url: string): Promise<ArrayBuffer | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    return await response.arrayBuffer();
  } catch {
    return null;
  }
}

let pending: Promise<BakedParts> | undefined;

/**
 * The baked sets, fetched and decoded once and shared by every caller. `baseUrl` follows
 * Vite's, so the same code works at the site root in development and under the deploy's
 * subpath.
 */
export function loadBakedParts(baseUrl: string = import.meta.env.BASE_URL): Promise<BakedParts> {
  pending ??= (async () => {
    const [connectionBytes, occupancyBytes] = await Promise.all([
      fetchBinary(`${baseUrl}baked/connections.bin`),
      fetchBinary(`${baseUrl}baked/occupancy.bin`),
    ]);
    const connections = connectionBytes === null ? null : unpackConnections(connectionBytes);
    const occupancy = occupancyBytes === null ? null : unpackOccupancy(occupancyBytes);
    if (connections === null && occupancy === null) return EMPTY;
    return {
      connections: connections ?? new Map(),
      occupancy: occupancy ?? new Map(),
    };
  })();
  return pending;
}

/** Drops the cached load, so a test can serve different bytes. */
export function resetBakedParts(): void {
  pending = undefined;
}
