/**
 * Curated metadata for the bundled model corpus, keyed by the `.mpd` slug under
 * `public/models/`. `tools/build-model-manifests.ts` merges this with what it derives
 * from parsing each file (brick count, unique parts, submodels, steps) to produce
 * `public/models/index.json`.
 *
 * The LDraw Official Model Repository (`library.ldraw.org/omr`) has no bulk API and no
 * CORS headers, so this is a hand-curated mirror rather than a live scrape: each `.mpd`
 * was downloaded once from `library.ldraw.org/library/omr/<set>-1.mpd` and committed
 * under `public/models/`, the same "hosted, same-origin, fetched on demand" tier
 * `docs/PREBAKE.md` already uses for part geometry. `officialPieceCount` is the LEGO
 * set's published piece count — usually close to but not identical to the parsed
 * `brickCount`, since decorated/sticker variants and some minifig accessories are not
 * always modelled.
 */
import type { ModelCuration } from '../src/features/omr/types.ts';

export interface CatalogEntry {
  name: string;
  setNumber: string;
  theme: string;
  year: number;
  officialPieceCount: number;
  curated: ModelCuration;
}

export const MODEL_CATALOG: Readonly<Record<string, CatalogEntry>> = {
  // ── previously bundled ──────────────────────────────────────────────────
  '1713-shipwrecked-pirate': {
    name: 'Shipwrecked Pirate',
    setNumber: '1713',
    theme: 'Pirates',
    year: 1992,
    officialPieceCount: 29,
    curated: null,
  },
  '10156-lego-truck': {
    name: 'LEGO Truck',
    setNumber: '10156',
    theme: 'Town',
    year: 2004,
    officialPieceCount: 425,
    curated: 'popular',
  },
  '21109-exo-suit': {
    name: 'Exo Suit',
    setNumber: '21109',
    theme: 'Ideas',
    year: 2014,
    officialPieceCount: 528,
    curated: 'popular',
  },
  '928-galaxy-explorer': {
    name: 'Galaxy Explorer',
    setNumber: '928',
    theme: 'Classic Space',
    year: 1979,
    officialPieceCount: 227,
    curated: 'popular',
  },
  '21309-nasa-apollo-saturn-v': {
    name: 'NASA Apollo Saturn V',
    setNumber: '21309',
    theme: 'Ideas',
    year: 2017,
    officialPieceCount: 1969,
    curated: 'jumbo',
  },
  // ── new, sourced from library.ldraw.org/omr ─────────────────────────────
  '10242-mini-cooper': {
    name: 'Mini Cooper',
    setNumber: '10242',
    theme: 'Creator Expert',
    year: 2014,
    officialPieceCount: 1077,
    curated: 'popular',
  },
  '75054-at-at': {
    name: 'AT-AT',
    setNumber: '75054',
    theme: 'Star Wars',
    year: 2014,
    officialPieceCount: 1137,
    curated: 'popular',
  },
  '10248-ferrari-f40': {
    name: 'Ferrari F40',
    setNumber: '10248',
    theme: 'Creator Expert',
    year: 2015,
    officialPieceCount: 1158,
    curated: 'popular',
  },
  '10271-fiat-500': {
    name: 'Fiat 500',
    setNumber: '10271',
    theme: 'Creator Expert',
    year: 2020,
    officialPieceCount: 960,
    curated: 'popular',
  },
  '10143-death-star-ii': {
    name: 'Death Star II',
    setNumber: '10143',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2005,
    officialPieceCount: 3441,
    curated: 'jumbo',
  },
  '10256-taj-mahal': {
    name: 'Taj Mahal',
    setNumber: '10256',
    theme: 'Creator Expert',
    year: 2017,
    officialPieceCount: 5923,
    curated: null,
  },
  '10241-maersk-triple-e': {
    name: 'Maersk Line Triple-E',
    setNumber: '10241',
    theme: 'Creator Expert',
    year: 2013,
    officialPieceCount: 1518,
    curated: null,
  },
  '21319-central-perk': {
    name: 'Central Perk',
    setNumber: '21319',
    theme: 'Ideas',
    year: 2019,
    officialPieceCount: 1070,
    curated: 'popular',
  },
  '10269-harley-davidson-fat-boy': {
    name: 'Harley-Davidson Fat Boy',
    setNumber: '10269',
    theme: 'Creator Expert',
    year: 2020,
    officialPieceCount: 1023,
    curated: 'popular',
  },
  '75060-slave-i': {
    name: 'Slave I',
    setNumber: '75060',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2015,
    officialPieceCount: 1996,
    curated: null,
  },
  '10280-flower-bouquet': {
    name: 'Flower Bouquet',
    setNumber: '10280',
    theme: 'Botanical Collection',
    year: 2021,
    officialPieceCount: 756,
    curated: 'popular',
  },
  '21042-statue-of-liberty': {
    name: 'Statue of Liberty',
    setNumber: '21042',
    theme: 'Architecture',
    year: 2018,
    officialPieceCount: 1685,
    curated: null,
  },
  '10253-big-ben': {
    name: 'Big Ben',
    setNumber: '10253',
    theme: 'Creator Expert',
    year: 2016,
    officialPieceCount: 4163,
    curated: null,
  },
  '10272-old-trafford': {
    name: 'Old Trafford - Manchester United',
    setNumber: '10272',
    theme: 'Creator Expert',
    year: 2020,
    officialPieceCount: 3898,
    curated: null,
  },
  '10276-colosseum': {
    name: 'Colosseum',
    setNumber: '10276',
    theme: 'Creator Expert',
    year: 2020,
    officialPieceCount: 9036,
    curated: 'jumbo',
  },
  '10278-police-station': {
    name: 'Police Station',
    setNumber: '10278',
    theme: 'Creator Expert',
    year: 2020,
    officialPieceCount: 2923,
    curated: null,
  },
  '10281-bonsai-tree': {
    name: 'Bonsai Tree',
    setNumber: '10281',
    theme: 'Botanical Collection',
    year: 2021,
    officialPieceCount: 878,
    curated: 'popular',
  },
  '10283-nasa-space-shuttle-discovery': {
    name: 'NASA Space Shuttle Discovery',
    setNumber: '10283',
    theme: 'Creator Expert',
    year: 2021,
    officialPieceCount: 2354,
    curated: null,
  },
  '10294-titanic': {
    name: 'Titanic',
    setNumber: '10294',
    theme: 'Creator Expert',
    year: 2021,
    officialPieceCount: 9090,
    curated: 'jumbo',
  },
  '10295-porsche-911': {
    name: 'Porsche 911',
    setNumber: '10295',
    theme: 'Creator Expert',
    year: 2021,
    officialPieceCount: 1458,
    curated: null,
  },
  '10297-boutique-hotel': {
    name: 'Boutique Hotel',
    setNumber: '10297',
    theme: 'Creator Expert',
    year: 2022,
    officialPieceCount: 3066,
    curated: null,
  },
  '10298-vespa-125': {
    name: 'Vespa 125',
    setNumber: '10298',
    theme: 'Creator Expert',
    year: 2021,
    officialPieceCount: 1106,
    curated: 'popular',
  },
  '10220-vw-t1-camper-van': {
    name: 'Volkswagen T1 Camper Van',
    setNumber: '10220',
    theme: 'Creator Expert',
    year: 2011,
    officialPieceCount: 1334,
    curated: 'popular',
  },
  '10243-parisian-restaurant': {
    name: 'Parisian Restaurant',
    setNumber: '10243',
    theme: 'Creator Expert (Modular)',
    year: 2014,
    officialPieceCount: 2469,
    curated: null,
  },
  '10252-vw-beetle': {
    name: 'Volkswagen Beetle',
    setNumber: '10252',
    theme: 'Creator Expert',
    year: 2016,
    officialPieceCount: 1167,
    curated: 'popular',
  },
  '10261-roller-coaster': {
    name: 'Roller Coaster',
    setNumber: '10261',
    theme: 'Creator Expert',
    year: 2018,
    officialPieceCount: 4124,
    curated: null,
  },
  '10262-aston-martin-db5': {
    name: 'Aston Martin DB5',
    setNumber: '10262',
    theme: 'Creator Expert',
    year: 2018,
    officialPieceCount: 1295,
    curated: 'popular',
  },
  '10270-bookshop': {
    name: 'Bookshop',
    setNumber: '10270',
    theme: 'Creator Expert (Modular)',
    year: 2020,
    officialPieceCount: 2504,
    curated: null,
  },
  '21323-grand-piano': {
    name: 'Grand Piano',
    setNumber: '21323',
    theme: 'Ideas',
    year: 2020,
    officialPieceCount: 3662,
    curated: null,
  },
  '42056-porsche-911-gt3-rs': {
    name: 'Porsche 911 GT3 RS',
    setNumber: '42056',
    theme: 'Technic',
    year: 2016,
    officialPieceCount: 2704,
    curated: null,
  },
  '42083-bugatti-chiron': {
    name: 'Bugatti Chiron',
    setNumber: '42083',
    theme: 'Technic',
    year: 2018,
    officialPieceCount: 3599,
    curated: 'jumbo',
  },
  '42115-lamborghini-sian': {
    name: 'Lamborghini Sián FKP 37',
    setNumber: '42115',
    theme: 'Technic',
    year: 2020,
    officialPieceCount: 3696,
    curated: null,
  },
  // Parses to ~190k flattened bricks against an official count of 3854 — deep nested
  // submodel reuse in the tread/motor rigging multiplies out far beyond the physical
  // part count. Left in deliberately as the most extreme stress case in the corpus;
  // see the model import report for measured load time.
  '42131-cat-d11-bulldozer': {
    name: 'Cat D11 Bulldozer',
    setNumber: '42131',
    theme: 'Technic',
    year: 2022,
    officialPieceCount: 3854,
    curated: 'jumbo',
  },
  '75144-snowspeeder': {
    name: 'Snowspeeder',
    setNumber: '75144',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2017,
    officialPieceCount: 1703,
    curated: null,
  },
  '76139-1989-batmobile': {
    name: '1989 Batmobile',
    setNumber: '76139',
    theme: 'DC',
    year: 2019,
    officialPieceCount: 3306,
    curated: null,
  },
  // ── expansion to 200, sourced from library.ldraw.org/omr ────────────────
  '21029-buckingham-palace': {
    name: 'Buckingham Palace',
    setNumber: '21029',
    theme: 'Architecture',
    year: 2016,
    officialPieceCount: 780,
    curated: null,
  },
  '21030-united-states-capitol-building': {
    name: 'United States Capitol Building',
    setNumber: '21030',
    theme: 'Architecture',
    year: 2016,
    officialPieceCount: 1032,
    curated: 'popular',
  },
  '21031-burj-khalifa': {
    name: 'Burj Khalifa',
    setNumber: '21031',
    theme: 'Architecture',
    year: 2016,
    officialPieceCount: 333,
    curated: null,
  },
  '21032-sydney': {
    name: 'Sydney',
    setNumber: '21032',
    theme: 'Architecture',
    year: 2017,
    officialPieceCount: 361,
    curated: null,
  },
  '21033-chicago': {
    name: 'Chicago',
    setNumber: '21033',
    theme: 'Architecture',
    year: 2017,
    officialPieceCount: 444,
    curated: null,
  },
  '21034-london': {
    name: 'London',
    setNumber: '21034',
    theme: 'Architecture',
    year: 2016,
    officialPieceCount: 468,
    curated: null,
  },
  '21035-solomon-r-guggenheim-museum': {
    name: 'Solomon R. Guggenheim Museum',
    setNumber: '21035',
    theme: 'Architecture',
    year: 2017,
    officialPieceCount: 744,
    curated: null,
  },
  '21036-arc-de-triomphe': {
    name: 'Arc de Triomphe',
    setNumber: '21036',
    theme: 'Architecture',
    year: 2017,
    officialPieceCount: 386,
    curated: null,
  },
  '21037-lego-house': {
    name: 'LEGO House',
    setNumber: '21037',
    theme: 'Architecture',
    year: 2017,
    officialPieceCount: 774,
    curated: 'popular',
  },
  '21039-shanghai': {
    name: 'Shanghai',
    setNumber: '21039',
    theme: 'Architecture',
    year: 2018,
    officialPieceCount: 597,
    curated: null,
  },
  '21041-great-wall-of-china': {
    name: 'Great Wall of China',
    setNumber: '21041',
    theme: 'Architecture',
    year: 2018,
    officialPieceCount: 550,
    curated: null,
  },
  '21043-san-francisco': {
    name: 'San Francisco',
    setNumber: '21043',
    theme: 'Architecture',
    year: 2019,
    officialPieceCount: 565,
    curated: null,
  },
  '21045-trafalgar-square': {
    name: 'Trafalgar Square',
    setNumber: '21045',
    theme: 'Architecture',
    year: 2019,
    officialPieceCount: 1197,
    curated: null,
  },
  '21046-empire-state-building': {
    name: 'Empire State Building',
    setNumber: '21046',
    theme: 'Architecture',
    year: 2019,
    officialPieceCount: 1767,
    curated: 'popular',
  },
  '21047-las-vegas': {
    name: 'Las Vegas',
    setNumber: '21047',
    theme: 'Architecture',
    year: 2018,
    officialPieceCount: 501,
    curated: null,
  },
  '21051-tokyo': {
    name: 'Tokyo',
    setNumber: '21051',
    theme: 'Architecture',
    year: 2020,
    officialPieceCount: 547,
    curated: null,
  },
  '21052-dubai': {
    name: 'Dubai',
    setNumber: '21052',
    theme: 'Architecture',
    year: 2020,
    officialPieceCount: 740,
    curated: null,
  },
  '40456-mickey-mouse': {
    name: 'Mickey Mouse',
    setNumber: '40456',
    theme: 'Brick Sketches',
    year: 2021,
    officialPieceCount: 118,
    curated: null,
  },
  '6080-king-s-castle': {
    name: 'King\'s Castle',
    setNumber: '6080',
    theme: 'Castle',
    year: 1984,
    officialPieceCount: 679,
    curated: 'popular',
  },
  '60216-downtown-fire-brigade': {
    name: 'Downtown Fire Brigade',
    setNumber: '60216',
    theme: 'City',
    year: 2019,
    officialPieceCount: 943,
    curated: 'popular',
  },
  '6929-star-fleet-voyager': {
    name: 'Star Fleet Voyager',
    setNumber: '6929',
    theme: 'Classic Space',
    year: 1981,
    officialPieceCount: 246,
    curated: 'popular',
  },
  '6939-saucer-centurion': {
    name: 'Saucer Centurion',
    setNumber: '6939',
    theme: 'Classic Space',
    year: 1994,
    officialPieceCount: 222,
    curated: null,
  },
  '6953-cosmic-laser-launcher': {
    name: 'Cosmic Laser Launcher',
    setNumber: '6953',
    theme: 'Classic Space',
    year: 1987,
    officialPieceCount: 210,
    curated: null,
  },
  '6954-renegade': {
    name: 'Renegade',
    setNumber: '6954',
    theme: 'Classic Space',
    year: 1987,
    officialPieceCount: 315,
    curated: null,
  },
  '6955-space-lock-up-isolation-base': {
    name: 'Space Lock-Up Isolation Base',
    setNumber: '6955',
    theme: 'Classic Space',
    year: 1989,
    officialPieceCount: 252,
    curated: null,
  },
  '6956-stellar-recon-voyager': {
    name: 'Stellar Recon Voyager',
    setNumber: '6956',
    theme: 'Classic Space',
    year: 1990,
    officialPieceCount: 233,
    curated: null,
  },
  '6957-solar-snooper': {
    name: 'Solar Snooper',
    setNumber: '6957',
    theme: 'Classic Space',
    year: 1992,
    officialPieceCount: 253,
    curated: null,
  },
  '6959-lunar-launch-site': {
    name: 'Lunar Launch Site',
    setNumber: '6959',
    theme: 'Classic Space',
    year: 1994,
    officialPieceCount: 288,
    curated: null,
  },
  '6970-beta-i-command-base': {
    name: 'Beta I Command Base',
    setNumber: '6970',
    theme: 'Classic Space',
    year: 1980,
    officialPieceCount: 270,
    curated: null,
  },
  '6973-deep-freeze-defender': {
    name: 'Deep Freeze Defender',
    setNumber: '6973',
    theme: 'Classic Space',
    year: 1993,
    officialPieceCount: 417,
    curated: null,
  },
  '6980-galaxy-commander': {
    name: 'Galaxy Commander',
    setNumber: '6980',
    theme: 'Classic Space',
    year: 1983,
    officialPieceCount: 443,
    curated: 'popular',
  },
  '6981-aerial-intruder': {
    name: 'Aerial Intruder',
    setNumber: '6981',
    theme: 'Classic Space',
    year: 1991,
    officialPieceCount: 267,
    curated: null,
  },
  '6983-ice-station-odyssey': {
    name: 'Ice Station Odyssey',
    setNumber: '6983',
    theme: 'Classic Space',
    year: 1993,
    officialPieceCount: 344,
    curated: null,
  },
  '6984-galactic-mediator': {
    name: 'Galactic Mediator',
    setNumber: '6984',
    theme: 'Classic Space',
    year: 1992,
    officialPieceCount: 406,
    curated: null,
  },
  '6986-mission-commander': {
    name: 'Mission Commander',
    setNumber: '6986',
    theme: 'Classic Space',
    year: 1989,
    officialPieceCount: 477,
    curated: null,
  },
  '6987-message-intercept-base': {
    name: 'Message Intercept Base',
    setNumber: '6987',
    theme: 'Classic Space',
    year: 1988,
    officialPieceCount: 575,
    curated: null,
  },
  '6988-alpha-centauri-outpost': {
    name: 'Alpha Centauri Outpost',
    setNumber: '6988',
    theme: 'Classic Space',
    year: 1991,
    officialPieceCount: 406,
    curated: null,
  },
  '6989-mega-core-magnetizer': {
    name: 'Mega Core Magnetizer',
    setNumber: '6989',
    theme: 'Classic Space',
    year: 1990,
    officialPieceCount: 506,
    curated: null,
  },
  '6990-monorail-transport-system': {
    name: 'Monorail Transport System',
    setNumber: '6990',
    theme: 'Classic Space',
    year: 1988,
    officialPieceCount: 731,
    curated: null,
  },
  '6991-monorail-transport-base': {
    name: 'Monorail Transport Base',
    setNumber: '6991',
    theme: 'Classic Space',
    year: 1994,
    officialPieceCount: 573,
    curated: null,
  },
  '4993-cool-convertible': {
    name: 'Cool Convertible',
    setNumber: '4993',
    theme: 'Creator',
    year: 2008,
    officialPieceCount: 648,
    curated: null,
  },
  '5766-log-cabin': {
    name: 'Log Cabin',
    setNumber: '5766',
    theme: 'Creator',
    year: 2011,
    officialPieceCount: 355,
    curated: null,
  },
  '5771-hillside-house': {
    name: 'Hillside House',
    setNumber: '5771',
    theme: 'Creator',
    year: 2011,
    officialPieceCount: 714,
    curated: null,
  },
  '5891-apple-tree-house': {
    name: 'Apple Tree House',
    setNumber: '5891',
    theme: 'Creator',
    year: 2010,
    officialPieceCount: 539,
    curated: 'popular',
  },
  '5892-sonic-boom': {
    name: 'Sonic Boom',
    setNumber: '5892',
    theme: 'Creator',
    year: 2010,
    officialPieceCount: 539,
    curated: null,
  },
  '6753-highway-transport': {
    name: 'Highway Transport',
    setNumber: '6753',
    theme: 'Creator',
    year: 2009,
    officialPieceCount: 1294,
    curated: null,
  },
  '10267-gingerbread-house': {
    name: 'Gingerbread House',
    setNumber: '10267',
    theme: 'Creator',
    year: 2019,
    officialPieceCount: 1477,
    curated: 'popular',
  },
  '10124-wright-flyer': {
    name: 'Wright Flyer',
    setNumber: '10124',
    theme: 'Creator Expert',
    year: 2003,
    officialPieceCount: 663,
    curated: null,
  },
  '10194-emerald-night': {
    name: 'Emerald Night',
    setNumber: '10194',
    theme: 'Creator Expert',
    year: 2009,
    officialPieceCount: 1091,
    curated: 'popular',
  },
  '10213-shuttle-adventure': {
    name: 'Shuttle Adventure',
    setNumber: '10213',
    theme: 'Creator Expert',
    year: 2010,
    officialPieceCount: 1204,
    curated: null,
  },
  '10214-tower-bridge': {
    name: 'Tower Bridge',
    setNumber: '10214',
    theme: 'Creator Expert',
    year: 2010,
    officialPieceCount: 4295,
    curated: 'jumbo',
  },
  '10226-sopwith-camel': {
    name: 'Sopwith Camel',
    setNumber: '10226',
    theme: 'Creator Expert',
    year: 2012,
    officialPieceCount: 879,
    curated: null,
  },
  '10233-horizon-express': {
    name: 'Horizon Express',
    setNumber: '10233',
    theme: 'Creator Expert',
    year: 2013,
    officialPieceCount: 1351,
    curated: null,
  },
  '10258-london-bus': {
    name: 'London Bus',
    setNumber: '10258',
    theme: 'Creator Expert',
    year: 2017,
    officialPieceCount: 1686,
    curated: 'popular',
  },
  '10265-ford-mustang': {
    name: 'Ford Mustang',
    setNumber: '10265',
    theme: 'Creator Expert',
    year: 2019,
    officialPieceCount: 1471,
    curated: 'popular',
  },
  '10182-cafe-corner': {
    name: 'Cafe Corner',
    setNumber: '10182',
    theme: 'Creator Expert (Modular)',
    year: 2007,
    officialPieceCount: 2058,
    curated: 'popular',
  },
  '10185-green-grocer': {
    name: 'Green Grocer',
    setNumber: '10185',
    theme: 'Creator Expert (Modular)',
    year: 2008,
    officialPieceCount: 2358,
    curated: 'popular',
  },
  '10190-market-street': {
    name: 'Market Street',
    setNumber: '10190',
    theme: 'Creator Expert (Modular)',
    year: 2007,
    officialPieceCount: 1250,
    curated: null,
  },
  '10197-fire-brigade': {
    name: 'Fire Brigade',
    setNumber: '10197',
    theme: 'Creator Expert (Modular)',
    year: 2009,
    officialPieceCount: 2236,
    curated: 'popular',
  },
  '10218-pet-shop': {
    name: 'Pet Shop',
    setNumber: '10218',
    theme: 'Creator Expert (Modular)',
    year: 2011,
    officialPieceCount: 2034,
    curated: null,
  },
  '10224-town-hall': {
    name: 'Town Hall',
    setNumber: '10224',
    theme: 'Creator Expert (Modular)',
    year: 2012,
    officialPieceCount: 2772,
    curated: 'jumbo',
  },
  '10246-detective-s-office': {
    name: 'Detective\'s Office',
    setNumber: '10246',
    theme: 'Creator Expert (Modular)',
    year: 2015,
    officialPieceCount: 2262,
    curated: null,
  },
  '10251-brick-bank': {
    name: 'Brick Bank',
    setNumber: '10251',
    theme: 'Creator Expert (Modular)',
    year: 2016,
    officialPieceCount: 2384,
    curated: 'popular',
  },
  '10264-corner-garage': {
    name: 'Corner Garage',
    setNumber: '10264',
    theme: 'Creator Expert (Modular)',
    year: 2019,
    officialPieceCount: 2569,
    curated: 'jumbo',
  },
  '76161-1989-batwing': {
    name: '1989 Batwing',
    setNumber: '76161',
    theme: 'DC',
    year: 2020,
    officialPieceCount: 2363,
    curated: 'popular',
  },
  '75954-hogwarts-great-hall': {
    name: 'Hogwarts Great Hall',
    setNumber: '75954',
    theme: 'Harry Potter',
    year: 2018,
    officialPieceCount: 882,
    curated: 'popular',
  },
  '75980-attack-on-the-burrow': {
    name: 'Attack on The Burrow',
    setNumber: '75980',
    theme: 'Harry Potter',
    year: 2020,
    officialPieceCount: 1052,
    curated: null,
  },
  '10277-crocodile-locomotive': {
    name: 'Crocodile Locomotive',
    setNumber: '10277',
    theme: 'Icons',
    year: 2020,
    officialPieceCount: 1279,
    curated: null,
  },
  '10315-tranquil-garden': {
    name: 'Tranquil Garden',
    setNumber: '10315',
    theme: 'Icons',
    year: 2023,
    officialPieceCount: 1363,
    curated: null,
  },
  '21302-the-big-bang-theory': {
    name: 'The Big Bang Theory',
    setNumber: '21302',
    theme: 'Ideas',
    year: 2015,
    officialPieceCount: 498,
    curated: null,
  },
  '21303-wall-e-original-version': {
    name: 'WALL•E [Original Version]',
    setNumber: '21303',
    theme: 'Ideas',
    year: 2015,
    officialPieceCount: 677,
    curated: null,
  },
  '21307-caterham-seven-620r': {
    name: 'Caterham Seven 620R',
    setNumber: '21307',
    theme: 'Ideas',
    year: 2016,
    officialPieceCount: 771,
    curated: null,
  },
  '21311-voltron': {
    name: 'Voltron',
    setNumber: '21311',
    theme: 'Ideas',
    year: 2018,
    officialPieceCount: 2321,
    curated: 'popular',
  },
  '21318-tree-house': {
    name: 'Tree House',
    setNumber: '21318',
    theme: 'Ideas',
    year: 2019,
    officialPieceCount: 3037,
    curated: 'jumbo',
  },
  '21321-international-space-station': {
    name: 'International Space Station',
    setNumber: '21321',
    theme: 'Ideas',
    year: 2020,
    officialPieceCount: 864,
    curated: 'popular',
  },
  '21325-medieval-blacksmith': {
    name: 'Medieval Blacksmith',
    setNumber: '21325',
    theme: 'Ideas',
    year: 2021,
    officialPieceCount: 2164,
    curated: 'popular',
  },
  '40448-vintage-car': {
    name: 'Vintage Car',
    setNumber: '40448',
    theme: 'Ideas',
    year: 2021,
    officialPieceCount: 189,
    curated: null,
  },
  '10176-royal-king-s-castle': {
    name: 'Royal King\'s Castle',
    setNumber: '10176',
    theme: 'Knights Kingdom II',
    year: 2006,
    officialPieceCount: 877,
    curated: null,
  },
  '76042-the-shield-helicarrier': {
    name: 'The SHIELD Helicarrier',
    setNumber: '76042',
    theme: 'Marvel',
    year: 2015,
    officialPieceCount: 2996,
    curated: 'jumbo',
  },
  '10230-mini-modulars': {
    name: 'Mini Modulars',
    setNumber: '10230',
    theme: 'Mini',
    year: 2012,
    officialPieceCount: 1356,
    curated: null,
  },
  '5571-giant-truck': {
    name: 'Giant Truck',
    setNumber: '5571',
    theme: 'Model Team',
    year: 1996,
    officialPieceCount: 1746,
    curated: null,
  },
  '6279-skull-island': {
    name: 'Skull Island',
    setNumber: '6279',
    theme: 'Pirates',
    year: 1995,
    officialPieceCount: 386,
    curated: null,
  },
  '6285-black-seas-barracuda': {
    name: 'Black Seas Barracuda',
    setNumber: '6285',
    theme: 'Pirates',
    year: 1989,
    officialPieceCount: 915,
    curated: 'popular',
  },
  '6286-skull-s-eye-schooner': {
    name: 'Skull\'s Eye Schooner',
    setNumber: '6286',
    theme: 'Pirates',
    year: 1993,
    officialPieceCount: 925,
    curated: null,
  },
  '6964-boba-fett-s-slave-i-mini-kabaya-box': {
    name: 'Boba Fett\'s Slave I - Mini (Kabaya Box)',
    setNumber: '6964',
    theme: 'Star Wars',
    year: 2004,
    officialPieceCount: 25,
    curated: null,
  },
  '6965-tie-interceptor': {
    name: 'TIE Interceptor',
    setNumber: '6965',
    theme: 'Star Wars',
    year: 2004,
    officialPieceCount: 32,
    curated: null,
  },
  '6966-jedi-starfighter-mini': {
    name: 'Jedi Starfighter - Mini',
    setNumber: '6966',
    theme: 'Star Wars',
    year: 2005,
    officialPieceCount: 38,
    curated: null,
  },
  '6967-arc-170-starfighter-mini': {
    name: 'ARC-170 Starfighter - Mini',
    setNumber: '6967',
    theme: 'Star Wars',
    year: 2005,
    officialPieceCount: 42,
    curated: null,
  },
  '75102-poe-s-x-wing-fighter': {
    name: 'Poe\'s X-Wing Fighter',
    setNumber: '75102',
    theme: 'Star Wars',
    year: 2015,
    officialPieceCount: 716,
    curated: 'popular',
  },
  '10018-darth-maul': {
    name: 'Darth Maul',
    setNumber: '10018',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2001,
    officialPieceCount: 1868,
    curated: 'popular',
  },
  '10019-rebel-blockade-runner': {
    name: 'Rebel Blockade Runner',
    setNumber: '10019',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2001,
    officialPieceCount: 1748,
    curated: null,
  },
  '10030-imperial-star-destroyer': {
    name: 'Imperial Star Destroyer',
    setNumber: '10030',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2002,
    officialPieceCount: 3116,
    curated: 'jumbo',
  },
  '10129-rebel-snowspeeder': {
    name: 'Rebel Snowspeeder',
    setNumber: '10129',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2003,
    officialPieceCount: 1457,
    curated: null,
  },
  '10174-imperial-at-st': {
    name: 'Imperial AT-ST',
    setNumber: '10174',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2006,
    officialPieceCount: 1069,
    curated: null,
  },
  '10175-vader-s-tie-advanced': {
    name: 'Vader\'s TIE Advanced',
    setNumber: '10175',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2006,
    officialPieceCount: 1212,
    curated: null,
  },
  '10179-millennium-falcon': {
    name: 'Millennium Falcon',
    setNumber: '10179',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2007,
    officialPieceCount: 5198,
    curated: 'jumbo',
  },
  '10212-imperial-shuttle': {
    name: 'Imperial Shuttle',
    setNumber: '10212',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2010,
    officialPieceCount: 2503,
    curated: 'jumbo',
  },
  '10227-b-wing-starfighter': {
    name: 'B-wing Starfighter',
    setNumber: '10227',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2012,
    officialPieceCount: 1487,
    curated: null,
  },
  '10240-red-five-x-wing-starfighter': {
    name: 'Red Five X-Wing Starfighter',
    setNumber: '10240',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2013,
    officialPieceCount: 1558,
    curated: null,
  },
  '75181-y-wing-starfighter': {
    name: 'Y-Wing Starfighter',
    setNumber: '75181',
    theme: 'Star Wars Ultimate Collector Series',
    year: 2018,
    officialPieceCount: 1967,
    curated: 'popular',
  },
  '41999-4-x-4-crawler-exclusive-edition': {
    name: '4 x 4 Crawler Exclusive Edition',
    setNumber: '41999',
    theme: 'Technic',
    year: 2013,
    officialPieceCount: 1584,
    curated: null,
  },
  '42041-race-truck': {
    name: 'Race Truck',
    setNumber: '42041',
    theme: 'Technic',
    year: 2015,
    officialPieceCount: 608,
    curated: null,
  },
  '42042-crawler-crane': {
    name: 'Crawler Crane',
    setNumber: '42042',
    theme: 'Technic',
    year: 2015,
    officialPieceCount: 1400,
    curated: null,
  },
  '42043-mercedes-benz-arocs-3245': {
    name: 'Mercedes-Benz Arocs 3245',
    setNumber: '42043',
    theme: 'Technic',
    year: 2015,
    officialPieceCount: 2793,
    curated: 'jumbo',
  },
  '42055-bucket-wheel-excavator': {
    name: 'Bucket Wheel Excavator',
    setNumber: '42055',
    theme: 'Technic',
    year: 2016,
    officialPieceCount: 3929,
    curated: 'jumbo',
  },
  '42063-bmw-r-1200-gs-adventure': {
    name: 'BMW R 1200 GS Adventure',
    setNumber: '42063',
    theme: 'Technic',
    year: 2017,
    officialPieceCount: 603,
    curated: null,
  },
  '42070-6x6-all-terrain-tow-truck': {
    name: '6x6 All Terrain Tow Truck',
    setNumber: '42070',
    theme: 'Technic',
    year: 2017,
    officialPieceCount: 1862,
    curated: null,
  },
  '42078-mack-anthem': {
    name: 'Mack Anthem',
    setNumber: '42078',
    theme: 'Technic',
    year: 2018,
    officialPieceCount: 2595,
    curated: 'jumbo',
  },
  '42080-forest-machine': {
    name: 'Forest Machine',
    setNumber: '42080',
    theme: 'Technic',
    year: 2018,
    officialPieceCount: 1003,
    curated: null,
  },
  '42082-rough-terrain-crane': {
    name: 'Rough Terrain Crane',
    setNumber: '42082',
    theme: 'Technic',
    year: 2018,
    officialPieceCount: 4056,
    curated: 'jumbo',
  },
  '42093-chevrolet-corvette-zr1': {
    name: 'Chevrolet Corvette ZR1',
    setNumber: '42093',
    theme: 'Technic',
    year: 2019,
    officialPieceCount: 579,
    curated: null,
  },
  '42096-porsche-911-rsr': {
    name: 'Porsche 911 RSR',
    setNumber: '42096',
    theme: 'Technic',
    year: 2019,
    officialPieceCount: 1580,
    curated: null,
  },
  '42099-4x4-x-treme-off-roader': {
    name: '4x4 X-treme Off-Roader',
    setNumber: '42099',
    theme: 'Technic',
    year: 2019,
    officialPieceCount: 958,
    curated: null,
  },
  '42100-liebherr-r-9800-excavator': {
    name: 'Liebherr R 9800 Excavator',
    setNumber: '42100',
    theme: 'Technic',
    year: 2019,
    officialPieceCount: 4108,
    curated: 'jumbo',
  },
  '42107-ducati-panigale-v4-r': {
    name: 'Ducati Panigale V4 R',
    setNumber: '42107',
    theme: 'Technic',
    year: 2020,
    officialPieceCount: 646,
    curated: null,
  },
  '42109-app-controlled-top-gear-rally-car': {
    name: 'App-Controlled Top Gear Rally Car',
    setNumber: '42109',
    theme: 'Technic',
    year: 2020,
    officialPieceCount: 463,
    curated: null,
  },
  '42110-land-rover-defender': {
    name: 'Land Rover Defender',
    setNumber: '42110',
    theme: 'Technic',
    year: 2019,
    officialPieceCount: 2573,
    curated: 'jumbo',
  },
  '42111-dom-s-dodge-charger': {
    name: 'Dom\'s Dodge Charger',
    setNumber: '42111',
    theme: 'Technic',
    year: 2020,
    officialPieceCount: 1077,
    curated: null,
  },
  '42112-cement-mixer': {
    name: 'Cement Mixer',
    setNumber: '42112',
    theme: 'Technic',
    year: 2020,
    officialPieceCount: 1161,
    curated: null,
  },
  '42120-rescue-hovercraft': {
    name: 'Rescue Hovercraft',
    setNumber: '42120',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 457,
    curated: null,
  },
  '42121-heavy-duty-excavator': {
    name: 'Heavy-Duty Excavator',
    setNumber: '42121',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 569,
    curated: null,
  },
  '42122-jeep-wrangler': {
    name: 'Jeep Wrangler',
    setNumber: '42122',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 665,
    curated: null,
  },
  '42123-mclaren-senna-gtr': {
    name: 'McLaren Senna GTR',
    setNumber: '42123',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 830,
    curated: 'popular',
  },
  '42124-off-road-buggy': {
    name: 'Off-Road Buggy',
    setNumber: '42124',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 374,
    curated: null,
  },
  '42125-ferrari-488-gte-af-corse-51': {
    name: 'Ferrari 488 GTE "AF Corse #51"',
    setNumber: '42125',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 1684,
    curated: null,
  },
  '42129-4x4-mercedes-benz-zetros-trial-truck': {
    name: '4x4 Mercedes-Benz Zetros Trial Truck',
    setNumber: '42129',
    theme: 'Technic',
    year: 2021,
    officialPieceCount: 2131,
    curated: null,
  },
  '6350-pizza-to-go': {
    name: 'Pizza To Go',
    setNumber: '6350',
    theme: 'Town',
    year: 1994,
    officialPieceCount: 151,
    curated: null,
  },
  '6353-coastal-cutter': {
    name: 'Coastal Cutter',
    setNumber: '6353',
    theme: 'Town',
    year: 1991,
    officialPieceCount: 185,
    curated: null,
  },
  '6355-derby-trotter': {
    name: 'Derby Trotter',
    setNumber: '6355',
    theme: 'Town',
    year: 1989,
    officialPieceCount: 142,
    curated: null,
  },
  '6356-med-star-rescue-plane': {
    name: 'Med-Star Rescue Plane',
    setNumber: '6356',
    theme: 'Town',
    year: 1988,
    officialPieceCount: 160,
    curated: null,
  },
  '6357-stunt-copter-n-truck': {
    name: 'Stunt \'Copter N\' Truck',
    setNumber: '6357',
    theme: 'Town',
    year: 1988,
    officialPieceCount: 177,
    curated: null,
  },
  '6373-motorcycle-shop': {
    name: 'Motorcycle Shop',
    setNumber: '6373',
    theme: 'Town',
    year: 1984,
    officialPieceCount: 188,
    curated: null,
  },
  '6362-post-office': {
    name: 'Post Office',
    setNumber: '6362',
    theme: 'Town',
    year: 1982,
    officialPieceCount: 136,
    curated: null,
  },
  '6363-auto-service-station': {
    name: 'Auto Service Station',
    setNumber: '6363',
    theme: 'Town',
    year: 1980,
    officialPieceCount: 142,
    curated: null,
  },
  '6365-summer-cottage': {
    name: 'Summer Cottage',
    setNumber: '6365',
    theme: 'Town',
    year: 1981,
    officialPieceCount: 153,
    curated: null,
  },
  '6368-jet-airliner': {
    name: 'Jet Airliner',
    setNumber: '6368',
    theme: 'Town',
    year: 1985,
    officialPieceCount: 137,
    curated: null,
  },
  '6372-town-house': {
    name: 'Town House',
    setNumber: '6372',
    theme: 'Town',
    year: 1982,
    officialPieceCount: 235,
    curated: null,
  },
  '6374-holiday-home': {
    name: 'Holiday Home',
    setNumber: '6374',
    theme: 'Town',
    year: 1983,
    officialPieceCount: 266,
    curated: null,
  },
  '6375-trans-air-carrier': {
    name: 'Trans Air Carrier',
    setNumber: '6375',
    theme: 'Town',
    year: 1990,
    officialPieceCount: 205,
    curated: null,
  },
  '6378-shell-service-station': {
    name: 'Shell Service Station',
    setNumber: '6378',
    theme: 'Town',
    year: 1986,
    officialPieceCount: 292,
    curated: null,
  },
  '6380-emergency-treatment-center': {
    name: 'Emergency Treatment Center',
    setNumber: '6380',
    theme: 'Town',
    year: 1987,
    officialPieceCount: 293,
    curated: null,
  },
  '6382-fire-station': {
    name: 'Fire Station',
    setNumber: '6382',
    theme: 'Town',
    year: 1981,
    officialPieceCount: 396,
    curated: null,
  },
  '6386-police-command-base': {
    name: 'Police Command Base',
    setNumber: '6386',
    theme: 'Town',
    year: 1986,
    officialPieceCount: 397,
    curated: null,
  },
  '6389-fire-control-center': {
    name: 'Fire Control Center',
    setNumber: '6389',
    theme: 'Town',
    year: 1990,
    officialPieceCount: 540,
    curated: null,
  },
  '6392-airport': {
    name: 'Airport',
    setNumber: '6392',
    theme: 'Town',
    year: 1985,
    officialPieceCount: 538,
    curated: null,
  },
  '6397-gas-n-wash-express': {
    name: 'Gas N\' Wash Express',
    setNumber: '6397',
    theme: 'Town',
    year: 1992,
    officialPieceCount: 474,
    curated: null,
  },
  '6398-central-precinct-hq': {
    name: 'Central Precinct HQ',
    setNumber: '6398',
    theme: 'Town',
    year: 1993,
    officialPieceCount: 635,
    curated: null,
  },
  '6399-airport-shuttle': {
    name: 'Airport Shuttle',
    setNumber: '6399',
    theme: 'Town',
    year: 1990,
    officialPieceCount: 786,
    curated: null,
  },
  '6400-go-kart': {
    name: 'Go-Kart',
    setNumber: '6400',
    theme: 'Town',
    year: 1997,
    officialPieceCount: 23,
    curated: null,
  },
  '6462-aerial-recovery': {
    name: 'Aerial Recovery',
    setNumber: '6462',
    theme: 'Town',
    year: 1998,
    officialPieceCount: 205,
    curated: null,
  },
  '6540-pier-police': {
    name: 'Pier Police',
    setNumber: '6540',
    theme: 'Town',
    year: 1991,
    officialPieceCount: 357,
    curated: null,
  },
  '6541-intercoastal-seaport': {
    name: 'Intercoastal Seaport',
    setNumber: '6541',
    theme: 'Town',
    year: 1991,
    officialPieceCount: 551,
    curated: null,
  },
  '6553-crisis-news-crew': {
    name: 'Crisis News Crew',
    setNumber: '6553',
    theme: 'Town',
    year: 1997,
    officialPieceCount: 136,
    curated: null,
  },
  '6597-century-skyway': {
    name: 'Century Skyway',
    setNumber: '6597',
    theme: 'Town',
    year: 1994,
    officialPieceCount: 905,
    curated: null,
  },
  '6675-road-trail-4x4': {
    name: 'Road & Trail 4x4',
    setNumber: '6675',
    theme: 'Town',
    year: 1988,
    officialPieceCount: 81,
    curated: null,
  },
  '10159-city-airport': {
    name: 'City Airport',
    setNumber: '10159',
    theme: 'Town',
    year: 2004,
    officialPieceCount: 914,
    curated: null,
  },
  '10184-town-plan': {
    name: 'Town Plan',
    setNumber: '10184',
    theme: 'Town',
    year: 2008,
    officialPieceCount: 2011,
    curated: null,
  },
  '10001-metroliner': {
    name: 'Metroliner',
    setNumber: '10001',
    theme: 'Trains',
    year: 2001,
    officialPieceCount: 787,
    curated: null,
  },
  '10170-ttx-intermodal-double-stack-car': {
    name: 'TTX Intermodal Double-Stack Car',
    setNumber: '10170',
    theme: 'Trains',
    year: 2005,
    officialPieceCount: 366,
    curated: null,
  },
  '10205-locomotive': {
    name: 'Locomotive',
    setNumber: '10205',
    theme: 'Trains',
    year: 2002,
    officialPieceCount: 234,
    curated: null,
  },
};
